FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app ./app
COPY run.py .

ENV ENVIRONMENT=production
EXPOSE 3000

CMD ["python", "run.py"]
